<?php

return [
    'items' => [
        [
            'title' => 'Fullstack Developer',
            'title_en' => 'Fullstack Developer',
            'company' => 'Tureks Uluslararası Fuarcılık A.Ş.',
            'company_en' => 'Tureks International Fair Inc.',
            'type' => 'Tam zamanlı',
            'type_en' => 'Full-time',
            'date_start' => 'Eyl 2024',
            'date_start_en' => 'Sep 2024',
            'date_end' => 'Halen',
            'date_end_en' => 'Present',
            'duration' => '1 yıl 7 ay',
            'duration_en' => '1 yr 7 mo',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
            'work_mode' => 'Ofisten',
            'work_mode_en' => 'On-site',
        ],
        [
            'title' => 'Backend & Frontend Developer',
            'title_en' => 'Backend & Frontend Developer',
            'company' => 'Freelance',
            'company_en' => 'Freelance',
            'type' => 'Serbest çalışan',
            'type_en' => 'Self-employed',
            'date_start' => 'Ara 2023',
            'date_start_en' => 'Dec 2023',
            'date_end' => 'Eyl 2024',
            'date_end_en' => 'Sep 2024',
            'duration' => '10 ay',
            'duration_en' => '10 mo',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
            'work_mode' => 'Uzaktan',
            'work_mode_en' => 'Remote',
        ],
        [
            'title' => 'Art Director',
            'title_en' => 'Art Director',
            'company' => 'HairNeva Hair Transplant',
            'company_en' => 'HairNeva Hair Transplant',
            'type' => 'Tam zamanlı',
            'type_en' => 'Full-time',
            'date_start' => 'Nis 2017',
            'date_start_en' => 'Apr 2017',
            'date_end' => 'Ara 2023',
            'date_end_en' => 'Dec 2023',
            'duration' => '6 yıl 9 ay',
            'duration_en' => '6 yr 9 mo',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
        ],
        [
            'title' => 'Web Design & Development Specialist',
            'title_en' => 'Web Design & Development Specialist',
            'company' => 'TESAN İletişim',
            'company_en' => 'TESAN Communication',
            'type' => null,
            'type_en' => null,
            'date_start' => '2013',
            'date_start_en' => '2013',
            'date_end' => 'Şub 2017',
            'date_end_en' => 'Feb 2017',
            'duration' => '4 yıl 2 ay',
            'duration_en' => '4 yr 2 mo',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
        ],
        [
            'title' => 'Web Interface Designer',
            'title_en' => 'Web Interface Designer',
            'company' => 'Daynex E-Ticaret ve Web Çözümleri',
            'company_en' => 'Daynex E-Commerce & Web Solutions',
            'type' => null,
            'type_en' => null,
            'date_start' => '2012',
            'date_start_en' => '2012',
            'date_end' => '2013',
            'date_end_en' => '2013',
            'duration' => '1 yıl',
            'duration_en' => '1 yr',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
        ],
        [
            'title' => 'Web Design Specialist',
            'title_en' => 'Web Design Specialist',
            'company' => 'BTPAR Bilgi Teknolojileri',
            'company_en' => 'BTPAR Information Technologies',
            'type' => 'Tam zamanlı',
            'type_en' => 'Full-time',
            'date_start' => 'Oca 2009',
            'date_start_en' => 'Jan 2009',
            'date_end' => 'Oca 2012',
            'date_end_en' => 'Jan 2012',
            'duration' => '3 yıl 1 ay',
            'duration_en' => '3 yr 1 mo',
            'location' => 'İstanbul, Türkiye',
            'location_en' => 'Istanbul, Turkey',
        ],
    ],
];
